[package]
name = "scalar"
version = "0.1.0"
authors = ["csk <karthik-subramanyam.chakka@grenoble-inp.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
